import App from '../src/core/app.class';

export default function (app: App) {
  return [
    {
      id: 'toolbar',
      title: app.i10n('toolbar'),
      enabled: true,
      deps: ['react', 'antd'],
      priority: 70,
      run_at: 'dom_ready',
      option: {
        toolbar: {
          drag: true,
          table: 'toolbar',
          title: app.i10n('toolbar'),
          icon: 'ToolOutlined',
          type: 'icon-switch',
          tooltip: app.i10n('toolbar_msg'),
        },
        apps: {
          data: [
            {
              theme: true,
              type: 'switch',
              id: 'autohide',
              defaultValue: false,
              title: app.i10n('autohide'),
            },
            {
              min: 0,
              max: 50,
              unit: 'px',
              theme: true,
              id: 'itemspace',
              defaultValue: 10,
              title: app.i10n('itemspace'),
            },
            {
              min: 0,
              max: 50,
              unit: 'px',
              theme: true,
              id: 'groupspace',
              defaultValue: 10,
              title: app.i10n('groupspace'),
            },
          ],
        },
      },
    },
    {
      id: 'setting',
      title: app.i10n('setting'),
      core: true,
      enabled: true,
      deps: ['react', 'antd', 'codemirror'],
      priority: 50,
      option: {
        keys: {
          data: {
            setting: {
              title: app.i10n('open_setting'),
            },
            setting__account: {
              title: app.i10n('open_account'),
              priority: 600,
            },
            setting__style: {
              title: app.i10n('open_style'),
              priority: 601,
            },
            setting__skin: {
              title: app.i10n('open_skin'),
              priority: 602,
            },
            setting__toolbar: {
              title: app.i10n('open_toolbar'),
              priority: 605,
            },
            setting__keys: {
              title: app.i10n('open_keys'),
              priority: 606,
            },
            setting__menu: {
              title: app.i10n('open_menu'),
              priority: 607,
            },
            setting__lists: {
              title: app.i10n('open_lists'),
              priority: 608,
            },
            setting__basic: {
              title: app.i10n('open_basic'),
              priority: 609,
            },
            setting__stylesheet: {
              title: app.i10n('open_stylesheet'),
              priority: 610,
            },
            setting__about: {
              title: app.i10n('open_about'),
              priority: 612,
            },
          },
        },
        menu: {
          data: {
            setting: {
              title: app.i10n('open_setting'),
            },
            setting__account: {
              title: app.i10n('open_account'),
              priority: 600,
            },
            setting__style: {
              title: app.i10n('open_style'),
              priority: 601,
            },
            setting__skin: {
              title: app.i10n('open_skin'),
              priority: 602,
            },
            setting__toolbar: {
              title: app.i10n('open_toolbar'),
              priority: 605,
            },
            setting__keys: {
              title: app.i10n('open_keys'),
              priority: 606,
            },
            setting__menu: {
              title: app.i10n('open_menu'),
              priority: 607,
            },
            setting__lists: {
              title: app.i10n('open_lists'),
              priority: 608,
            },
            setting__basic: {
              title: app.i10n('open_basic'),
              priority: 609,
            },
            setting__stylesheet: {
              title: app.i10n('open_stylesheet'),
              priority: 610,
            },
            setting__about: {
              title: app.i10n('open_about'),
              priority: 612,
            },
          },
        },
        toolbar: {
          data: [
            {
              group: 0,
              id: 'setting',
              icon: 'SettingOutlined',
              title: app.i10n('open_setting'),
            },
            {
              group: 4,
              priority: 600,
              id: 'setting__account',
              icon: 'UserOutlined',
              title: app.i10n('open_account'),
            },
            {
              group: 4,
              priority: 601,
              id: 'setting__style',
              icon: 'FormatPainterOutlined',
              title: app.i10n('open_style'),
            },
            {
              group: 4,
              priority: 602,
              id: 'setting__skin',
              icon: 'SkinOutlined',
              title: app.i10n('open_skin'),
            },
            {
              group: 4,
              priority: 605,
              id: 'setting__toolbar',
              icon: 'ToolOutlined',
              title: app.i10n('open_toolbar'),
            },
            {
              group: 4,
              priority: 606,
              id: 'setting__keys',
              icon: 'ThunderboltOutlined',
              title: app.i10n('open_keys'),
            },
            {
              group: 4,
              priority: 607,
              id: 'setting__menu',
              icon: 'MenuOutlined',
              title: app.i10n('open_menu'),
            },
            {
              group: 4,
              priority: 608,
              id: 'setting__lists',
              icon: 'ProfileOutlined',
              title: app.i10n('open_lists'),
            },
            {
              group: 4,
              priority: 609,
              id: 'setting__apps',
              icon: 'AppstoreOutlined',
              title: app.i10n('open_apps'),
            },
            {
              group: 4,
              priority: 610,
              id: 'setting__stylesheet',
              icon: 'CodeOutlined',
              title: app.i10n('open_stylesheet'),
            },
            {
              group: 4,
              priority: 612,
              id: 'setting__about',
              icon: 'ExclamationCircleOutlined',
              title: app.i10n('open_about'),
            },
          ],
        },
        account: {
          priority: -10,
          title: app.i10n('account'),
          icon: 'UserOutlined',
          data: [
            {
              type: 'account',
              id: 'account',
              priority: 0,
            },
            {
              priority: 5,
              type: 'export',
              id: 'sync_export',
              hiddenLabel: true,
              title: app.i10n('sync_export'),
              data: [
                {
                  id: 'setting',
                  title: app.i10n('option'),
                },
                {
                  id: 'toolbar',
                  title: app.i10n('toolbar'),
                },
                {
                  id: 'keys',
                  title: app.i10n('keys'),
                },
                {
                  id: 'menu',
                  title: app.i10n('menu'),
                },
                {
                  id: 'lists',
                  title: app.i10n('lists'),
                },
                {
                  id: 'later',
                  title: app.i10n('later'),
                },
                {
                  id: 'annotator',
                  title: app.i10n('annotator'),
                },
                {
                  id: 'rule',
                  title: app.i10n('rule'),
                },
              ],
            },
            {
              priority: 6,
              type: 'import',
              id: 'sync_import',
              hiddenLabel: true,
              title: app.i10n('sync_import'),
              tooltip: app.i10n('sync_import_msg'),
            },
            {
              priority: 20,
              type: 'reset',
              id: 'reset',
              hiddenLabel: true,
              title: app.i10n('reset_all'),
            },
          ],
        },
        about: {
          priority: 200,
          title: app.i10n('about'),
          icon: 'ExclamationCircleOutlined',
          data: [
            {
              priority: 0,
              type: 'card',
              id: 'follow',
              hiddenLabel: true,
              title: app.i10n('follow'),
              tooltip: app.i10n('follow_msg'),
              data: [
                {
                  title: app.i10n('wechat'),
                  img: 'https://ranhe.xyz/post-images/wechat.png',
                },
                {
                  title: app.i10n('qq'),
                  path: 'https://qm.qq.com/cgi-bin/qm/qr?k=wseaRm8SdNiXCasA9RYwSbE_iMpblbqi&jump_from=webapi',
                },
              ],
            },
            {
              priority: 1,
              type: 'card',
              id: 'support',
              hiddenLabel: true,
              title: app.i10n('support'),
              tooltip: app.i10n('support_msg'),
              data: [
                {
                  title: app.i10n('donate_coffee'),
                  path: 'https://circlereader.com/donate',
                },
                {
                  title: app.i10n('share_to_other'),
                  path: 'https://ranhe.xyz/circle-share',
                },
              ],
            },
            {
              priority: 2,
              id: 'vote',
              type: 'vote',
              hiddenLabel: true,
              title: app.i10n('vote'),
              tooltip: app.i10n('vote_msg'),
              data: [
                {
                  id: 'vote',
                  type: 'primary',
                  title: app.i10n('to_vote'),
                },
                {
                  id: 'feedback',
                  title: app.i10n('to_feedback'),
                },
              ],
            },
            {
              priority: 3,
              type: 'card',
              id: 'link',
              hiddenLabel: true,
              title: app.i10n('links'),
              data: [
                {
                  title: app.i10n('website'),
                  path: '',
                  type: 'link',
                },
                {
                  title: app.i10n('usage'),
                  path: 'usage',
                  type: 'link',
                },
                {
                  title: app.i10n('agreement'),
                  path: 'agreement',
                  type: 'link',
                },
                {
                  title: app.i10n('privacy'),
                  path: 'privacy',
                  type: 'link',
                },
                {
                  title: app.i10n('faq'),
                  path: 'faq',
                  type: 'link',
                },
                {
                  title: app.i10n('update'),
                  path: 'changelog',
                  type: 'link',
                },
                {
                  title: app.i10n('feedback'),
                  path: 'feedback',
                  type: 'link',
                },
                {
                  title: app.i10n('download_latest'),
                  path: 'download',
                  type: 'link',
                },
                {
                  title: app.i10n('donate'),
                  path: 'donate',
                  type: 'link',
                },
              ],
            },
            {
              priority: 4,
              type: 'version',
              id: 'version',
            },
          ],
        },
      },
      data: {
        keys: {
          setting: {
            value: 's t',
            checked: true,
          },
          setting__account: {
            value: 's a',
            priority: 600,
          },
          setting__style: {
            value: 's l',
            priority: 601,
          },
          setting__skin: {
            value: 't m',
            priority: 602,
          },
          setting__toolbar: {
            value: 't b',
            priority: 605,
          },
          setting__keys: {
            value: '?',
            checked: true,
            priority: 606,
          },
          setting__menu: {
            value: 'c m',
            priority: 607,
          },
          setting__lists: {
            value: 'm w',
            priority: 608,
          },
          setting__basic: {
            value: 'b c',
            priority: 609,
          },
          setting__stylesheet: {
            value: 'c s',
            priority: 610,
          },
          setting__about: {
            value: 'a b',
            priority: 612,
          },
        },
        menu: {
          setting: {
            title: app.i10n('open_setting'),
            checked: true,
          },
          setting__account: {
            title: app.i10n('open_account'),
            priority: 600,
          },
          setting__style: {
            title: app.i10n('open_style'),
            priority: 601,
          },
          setting__skin: {
            title: app.i10n('open_skin'),
            priority: 602,
          },
          setting__toolbar: {
            title: app.i10n('open_toolbar'),
            priority: 605,
          },
          setting__keys: {
            title: app.i10n('open_keys'),
            priority: 606,
          },
          setting__menu: {
            title: app.i10n('open_menu'),
            priority: 607,
          },
          setting__lists: {
            title: app.i10n('open_lists'),
            priority: 608,
          },
          setting__basic: {
            title: app.i10n('open_basic'),
            priority: 609,
          },
          setting__stylesheet: {
            title: app.i10n('open_stylesheet'),
            priority: 610,
          },
          setting__about: {
            title: app.i10n('open_about'),
            priority: 612,
          },
        },
        toolbar: {
          setting: {
            group: 0,
            checked: true,
            icon: 'SettingOutlined',
            title: app.i10n('open_setting'),
          },
          setting__account: {
            group: 4,
            priority: 600,
            icon: 'UserOutlined',
            title: app.i10n('open_account'),
          },
          setting__style: {
            group: 4,
            priority: 601,
            icon: 'FormatPainterOutlined',
            title: app.i10n('open_style'),
          },
          setting__skin: {
            group: 4,
            priority: 602,
            icon: 'SkinOutlined',
            title: app.i10n('open_skin'),
          },
          setting__toolbar: {
            group: 4,
            checked: true,
            priority: 605,
            icon: 'ToolOutlined',
            title: app.i10n('open_toolbar'),
          },
          setting__keys: {
            group: 4,
            priority: 606,
            icon: 'ThunderboltOutlined',
            title: app.i10n('open_keys'),
          },
          setting__menu: {
            group: 4,
            priority: 607,
            icon: 'MenuOutlined',
            title: app.i10n('open_menu'),
          },
          setting__lists: {
            group: 4,
            priority: 608,
            icon: 'ProfileOutlined',
            title: app.i10n('open_lists'),
          },
          setting__apps: {
            group: 4,
            priority: 609,
            icon: 'AppstoreOutlined',
            title: app.i10n('open_apps'),
          },
          setting__stylesheet: {
            group: 4,
            priority: 610,
            icon: 'CodeOutlined',
            title: app.i10n('open_stylesheet'),
          },
          setting__about: {
            group: 4,
            priority: 612,
            icon: 'ExclamationCircleOutlined',
            title: app.i10n('open_about'),
          },
        },
      },
    },
    {
      id: 'render',
      title: app.i10n('render'),
      core: true,
      enabled: true,
      deps: ['react'],
      priority: 2,
      run_at: 'parser_ready',
      option: {
        style: {
          theme: true,
          night: true,
          limit: 12,
          priority: -8,
          title: app.i10n('style'),
          icon: 'FormatPainterOutlined',
          data: [
            {
              id: 'style_preset',
              type: 'style-preset',
              data: [
                {
                  id: 'default',
                  title: app.i10n('default'),
                  value: {
                    font: 'reset',
                    cnfont: 'reset',
                    align: 'reset',
                    blockspace: '20px',
                    imagealign: 'reset',
                    indent: '0em',
                    lineheight: 1.8,
                    size: '20px',
                    space: '0',
                    title1: '2em',
                    title1weight: 500,
                    title2: '1.6em',
                    title2weight: 500,
                    title3: '1.2em',
                    title3weight: 500,
                    title4: '1em',
                    title4weight: 500,
                    title5: '1em',
                    title5weight: 500,
                    title6: '1em',
                    title6weight: 500,
                    titlealign: 'reset',
                    weight: 400,
                    width: '800px',
                  },
                },
                {
                  id: 'regular',
                  title: app.i10n('compact'),
                  value: {
                    font: 'reset',
                    cnfont: 'reset',
                    align: 'reset',
                    blockspace: '28.8px',
                    imagealign: 'center',
                    indent: '2em',
                    lineheight: 1.8,
                    size: '18px',
                    space: '0',
                    title1: '1.2em',
                    title1weight: 400,
                    title2: '0.7em',
                    title2weight: 700,
                    title3: '1.2em',
                    title3weight: 400,
                    title4: '0.7em',
                    title4weight: 700,
                    title5: '0.7em',
                    title5weight: 700,
                    title6: '0.7em',
                    title6weight: 700,
                    titlealign: 'reset',
                    weight: 400,
                    width: '800px',
                  },
                },
                {
                  id: 'compact',
                  title: app.i10n('narrow_page'),
                  value: {
                    font: 'reset',
                    cnfont: 'reset',
                    align: 'reset',
                    blockspace: '13px',
                    imagealign: 'reset',
                    indent: '0em',
                    lineheight: 1.9,
                    size: '16px',
                    space: '0',
                    title1: '2em',
                    title1weight: 700,
                    title2: '1.2em',
                    title2weight: 700,
                    title3: '0.94em',
                    title3weight: 700,
                    title4: '1.2em',
                    title4weight: 700,
                    title5: '1em',
                    title5weight: 700,
                    title6: '0.6em',
                    title6weight: 700,
                    titlealign: 'center',
                    weight: 400,
                    width: '750px',
                  },
                },
                {
                  id: 'loose',
                  title: app.i10n('wide_page'),
                  value: {
                    font: 'reset',
                    cnfont: 'reset',
                    align: 'justify',
                    blockspace: '24px',
                    imagealign: 'center',
                    indent: '2em',
                    lineheight: 2,
                    size: '20px',
                    space: '0',
                    title1: '1.9em',
                    title1weight: 500,
                    title2: '0.8em',
                    title2weight: 400,
                    title3: '0.9em',
                    title3weight: 400,
                    title4: '0.9em',
                    title4weight: 400,
                    title5: '0.8em',
                    title5weight: 400,
                    title6: '0.6em',
                    title6weight: 700,
                    titlealign: 'center',
                    weight: 400,
                    width: '860px',
                  },
                },
              ],
            },
            {
              type: 'font',
              id: 'font',
              placement: 'topLeft',
              defaultValue: 'reset',
              title: app.i10n('font'),
              tooltip: app.i10n('font_tooltip'),
              learn_more: 'node/27',
              placeholder: app.i10n('default'),
            },
            {
              type: 'font',
              id: 'cnfont',
              placement: 'topLeft',
              defaultValue: 'reset',
              title: app.i10n('cn_font'),
              placeholder: app.i10n('default'),
            },
            {
              min: 12,
              max: 50,
              unit: 'px',
              id: 'size',
              defaultValue: 20,
              title: app.i10n('size'),
            },
            {
              min: 600,
              max: 2500,
              unit: 'px',
              id: 'width',
              defaultValue: 800,
              title: app.i10n('width'),
            },
            {
              max: 10,
              unit: 'px',
              id: 'space',
              defaultValue: 0,
              title: app.i10n('space'),
            },
            {
              min: 1,
              max: 3,
              step: 0.1,
              id: 'lineheight',
              defaultValue: 1.8,
              title: app.i10n('lineheight'),
            },
            {
              min: 100,
              max: 900,
              step: 100,
              id: 'weight',
              defaultValue: 400,
              title: app.i10n('weight'),
            },
            {
              max: 50,
              step: 2,
              unit: 'px',
              id: 'blockspace',
              defaultValue: 32,
              title: app.i10n('blockspace'),
            },
            {
              max: 10,
              unit: 'em',
              id: 'indent',
              defaultValue: 0,
              title: app.i10n('indent'),
            },
            {
              id: 'titlealign',
              title: app.i10n('titlealign'),
              type: 'align',
              defaultValue: 'reset',
              placeholder: app.i10n('default'),
            },
            {
              id: 'align',
              title: app.i10n('align'),
              type: 'align',
              defaultValue: 'reset',
              placeholder: app.i10n('default'),
            },
            {
              id: 'imagealign',
              title: app.i10n('imagealign'),
              type: 'align',
              defaultValue: 'reset',
              placeholder: app.i10n('default'),
            },
            {
              type: 'switch',
              id: 'imagehide',
              defaultValue: false,
              title: app.i10n('imagehide'),
            },
            {
              title: app.i10n('title1'),
            },
            {
              min: 1,
              max: 5,
              step: 0.1,
              unit: 'em',
              id: 'title1',
              defaultValue: 2,
              title: app.i10n('size'),
            },
            {
              min: 100,
              max: 900,
              step: 100,
              id: 'title1weight',
              defaultValue: 500,
              title: app.i10n('weight'),
            },
            {
              title: app.i10n('title2'),
            },
            {
              min: 1,
              max: 5,
              step: 0.1,
              unit: 'em',
              id: 'title2',
              defaultValue: 1.6,
              title: app.i10n('size'),
            },
            {
              min: 100,
              max: 900,
              step: 100,
              id: 'title2weight',
              defaultValue: 500,
              title: app.i10n('weight'),
            },
            {
              title: app.i10n('title3'),
            },
            {
              min: 1,
              max: 5,
              step: 0.1,
              unit: 'em',
              id: 'title3',
              defaultValue: 1.2,
              title: app.i10n('size'),
            },
            {
              min: 100,
              max: 900,
              step: 100,
              id: 'title3weight',
              defaultValue: 500,
              title: app.i10n('weight'),
            },
            {
              title: app.i10n('title4'),
            },
            {
              min: 1,
              max: 5,
              step: 0.1,
              unit: 'em',
              id: 'title4',
              defaultValue: 1,
              title: app.i10n('size'),
            },
            {
              min: 100,
              max: 900,
              step: 100,
              id: 'title4weight',
              defaultValue: 500,
              title: app.i10n('weight'),
            },
            {
              title: app.i10n('title5'),
            },
            {
              min: 1,
              max: 5,
              step: 0.1,
              unit: 'em',
              id: 'title5',
              defaultValue: 1,
              title: app.i10n('size'),
            },
            {
              min: 100,
              max: 900,
              step: 100,
              id: 'title5weight',
              defaultValue: 500,
              title: app.i10n('weight'),
            },
            {
              title: app.i10n('title6'),
            },
            {
              min: 1,
              max: 5,
              step: 0.1,
              unit: 'em',
              id: 'title6',
              defaultValue: 1,
              title: app.i10n('size'),
            },
            {
              min: 100,
              max: 900,
              step: 100,
              id: 'title6weight',
              defaultValue: 500,
              title: app.i10n('weight'),
            },
            {
              title: app.i10n('codehighlight'),
            },
            {
              title: app.i10n('codesize'),
              id: 'codesize',
              min: 12,
              max: 50,
              unit: 'px',
              defaultValue: 20,
            },
            {
              min: 1,
              max: 3,
              step: 0.1,
              title: app.i10n('codelineheight'),
              id: 'codelineheight',
              defaultValue: 1.8,
            },
          ],
        },
        skin: {
          theme: true,
          night: true,
          limit: 7,
          priority: -6,
          title: app.i10n('skin'),
          icon: 'SkinOutlined',
          data: [
            {
              type: 'color-preset',
              id: 'theme',
              data: [
                {
                  id: 'light',
                  data: {
                    color: '#1b1b1b',
                    backgroundColor: '#ffffff',
                  },
                  value: {
                    color: '#1b1b1b',
                    link: '#416ed2',
                    hover: '#305ab7',
                    visited: '#305ab7',
                    select: '#1b1b1b',
                    selectbg: '#bbd6fc',
                    bg: '#ffffff',
                    track: '#e2e2e2',
                    thumb: '#9e9e9e',
                    radius: '4px',
                  },
                },
                {
                  id: 'green',
                  data: {
                    color: '#282d2b',
                    backgroundColor: '#c7edcc',
                  },
                  value: {
                    color: '#282d2b',
                    link: '#507964',
                    hover: '#3e6b54',
                    visited: '#3e6b54',
                    select: '#000000',
                    selectbg: '#addab4',
                    bg: '#c7edcc',
                    track: '#8fbd95',
                    thumb: '#638c6d',
                    radius: '4px',
                  },
                },
                {
                  id: 'yellow',
                  data: {
                    color: '#4f321c',
                    backgroundColor: '#f8f1e3',
                  },
                  value: {
                    color: '#4f321c',
                    link: '#d19600',
                    hover: '#ad7d03',
                    visited: '#ad7d03',
                    select: '#4f321c',
                    selectbg: '#d19600',
                    bg: '#f8f1e3',
                    track: '#d6cfc1',
                    thumb: '#b3ac9c',
                    radius: '4px',
                  },
                },
                {
                  id: 'gray',
                  data: {
                    color: '#b0b0b0',
                    backgroundColor: '#4a4a4d',
                  },
                  value: {
                    color: '#b0b0b0',
                    link: '#5ac8fa',
                    hover: '#3ea4d2',
                    visited: '#3ea4d2',
                    select: '#fffefe',
                    selectbg: '#43b0e2',
                    bg: '#4a4a4d',
                    track: '#4e4e50',
                    thumb: '#83838c',
                    radius: '4px',
                  },
                },
                {
                  id: 'dark',
                  data: {
                    color: '#b0b0b0',
                    backgroundColor: '#121212',
                  },
                  value: {
                    color: '#b0b0b0',
                    link: '#5ac8fa',
                    hover: '#3ea4d2',
                    visited: '#3ea4d2',
                    select: '#fffefe',
                    selectbg: '#43b0e2',
                    bg: '#121212',
                    track: '#3c3a3a',
                    thumb: '#848484',
                    radius: '4px',
                  },
                },
              ],
            },
            {
              type: 'color-input',
              title: app.i10n('color'),
              id: 'color',
            },
            {
              type: 'color-input',
              title: app.i10n('link'),
              id: 'link',
            },
            {
              type: 'color-input',
              title: app.i10n('hover'),
              id: 'hover',
              tooltip: app.i10n('hover_tooltip'),
            },
            {
              type: 'color-input',
              title: app.i10n('visited'),
              id: 'visited',
              tooltip: app.i10n('visited_tooltip'),
            },
            {
              type: 'color-input',
              title: app.i10n('select'),
              id: 'select',
              tooltip: app.i10n('select_tooltip'),
            },
            {
              type: 'color-input',
              title: app.i10n('selectbg'),
              id: 'selectbg',
              tooltip: app.i10n('selectbg_tooltip'),
            },
            {
              type: 'bg',
              title: app.i10n('bg'),
              id: 'bg',
              hiddenLabel: true,
              data: [
                {
                  value: 'solid',
                  title: app.i10n('solid'),
                },
                {
                  value: 'gradient',
                  title: app.i10n('gradient'),
                },
                {
                  value: 'picture',
                  title: app.i10n('image'),
                },
              ],
            },
            {
              type: 'scrollbar',
              id: 'scrollbar',
              title: app.i10n('scrollbar'),
              data: [
                {
                  title: 'light',
                  data: {
                    borderRadius: 4,
                    outlineColor: '#e2e2e2',
                    border: '1px solid #f0eded',
                    backgroundColor: '#e2e2e2',
                    boxShadow: '20px 0px #9e9e9e inset',
                  },
                  value: {
                    track: '#e2e2e2',
                    thumb: '#9e9e9e',
                    radius: '4px',
                  },
                },
                {
                  title: 'green',
                  data: {
                    borderRadius: 4,
                    outlineColor: '#8faf98',
                    backgroundColor: '#8faf98',
                    boxShadow: '20px 0px #5a8064 inset',
                  },
                  value: {
                    track: '#8faf98',
                    thumb: '#5a8064',
                    radius: '4px',
                  },
                },
                {
                  title: 'yellow',
                  data: {
                    borderRadius: 4,
                    outlineColor: '#d6cfc1',
                    backgroundColor: '#d6cfc1',
                    boxShadow: '20px 0px #b3ac9c inset',
                  },
                  value: {
                    track: '#d6cfc1',
                    thumb: '#b3ac9c',
                    radius: '4px',
                  },
                },
                {
                  title: 'gray',
                  data: {
                    borderRadius: 4,
                    outlineColor: '#4e4e50',
                    backgroundColor: '#4e4e50',
                    boxShadow: '20px 0px #83838c inset',
                  },
                  value: {
                    track: '#4e4e50',
                    thumb: '#83838c',
                    radius: '4px',
                  },
                },
                {
                  title: 'dark',
                  data: {
                    borderRadius: 4,
                    outlineColor: '#3c3a3a',
                    backgroundColor: '#3c3a3a',
                    boxShadow: '20px 0px #848484 inset',
                  },
                  value: {
                    track: '#3c3a3a',
                    thumb: '#848484',
                    radius: '4px',
                  },
                },
              ],
            },
            {
              title: app.i10n('codehighlight'),
            },
            {
              type: 'color-input',
              title: app.i10n('codecomment'),
              id: 'codecomment',
              defaultValue: '#697070',
            },
            {
              type: 'color-input',
              title: app.i10n('codetag'),
              id: 'codetag',
              defaultValue: '#4444aa',
            },
            {
              type: 'color-input',
              title: app.i10n('codeattr'),
              id: 'codeattr',
              defaultValue: '#4444aa',
            },
            {
              type: 'color-input',
              title: app.i10n('codenumber'),
              id: 'codenumber',
              defaultValue: '#880000',
            },
            {
              type: 'color-input',
              title: app.i10n('codeblock'),
              id: 'codeblock',
              defaultValue: '#880000',
            },
            {
              type: 'color-input',
              title: app.i10n('codevariable'),
              id: 'codevariable',
              defaultValue: '#ab5656',
            },
            {
              type: 'color-input',
              title: app.i10n('codeliteral'),
              id: 'codeliteral',
              defaultValue: '#669955',
            },
            {
              type: 'color-input',
              title: app.i10n('codevalue'),
              id: 'code',
              defaultValue: '#397300',
            },
            {
              type: 'color-input',
              title: app.i10n('codemeta'),
              id: 'codemeta',
              defaultValue: '#1f7199',
            },
            {
              type: 'color-input',
              title: app.i10n('codestring'),
              id: 'codestring',
              defaultValue: '#3388aa',
            },
          ],
        },
        apps: {
          data: [
            {
              type: 'switch',
              id: 'removefooter',
              title: app.i10n('removefooter'),
            },
            {
              min: 0,
              max: 100,
              step: 1,
              unit: 'px',
              id: 'margin',
              theme: true,
              defaultValue: 80,
              title: app.i10n('margin'),
            },
            {
              min: 0,
              max: 100,
              step: 1,
              unit: 'px',
              id: 'padding',
              theme: true,
              defaultValue: 80,
              title: app.i10n('padding'),
              tooltip: app.i10n('padding_tooltip'),
            },
            {
              type: 'select',
              id: 'search_engine',
              title: app.i10n('search_engine'),
              tooltip: app.i10n('search_engine_tooltip'),
              defaultValue: 'https://www.baidu.com/s?wd=',
              data: [
                {
                  title: app.i10n('baidu'),
                  value: 'https://www.baidu.com/s?wd=',
                },
                {
                  title: app.i10n('sougou'),
                  value: 'https://www.sogou.com/web?query=',
                },
                {
                  title: app.i10n('bing'),
                  value: 'https://www.bing.com/search?q=',
                },
                {
                  title: app.i10n('google'),
                  value: 'https://www.google.com/search?q=',
                },
              ],
            },
          ],
        },
        keys: {
          data: {
            exit: {
              title: app.i10n('exit'),
              priority: 10,
            },
            exitclose: {
              title: app.i10n('exitclose'),
              priority: 20,
            },
            imagehide: {
              title: app.i10n('imagehide'),
              priority: 30,
            },
          },
        },
        menu: {
          data: {
            exit: {
              title: app.i10n('exit'),
              priority: 10,
            },
            exitclose: {
              title: app.i10n('exitclose'),
              priority: 20,
            },
            imagehide: {
              title: app.i10n('imagehide'),
              priority: 30,
            },
          },
        },
        toolbar: {
          data: [
            {
              group: 0,
              priority: 10,
              id: 'exit',
              icon: 'CloseOutlined',
              title: app.i10n('exit'),
            },
            {
              group: 0,
              priority: 20,
              id: 'exitclose',
              icon: 'PoweroffOutlined',
              title: app.i10n('exitclose'),
            },
            {
              group: 0,
              priority: 30,
              id: 'imagehide',
              icon: 'ImageHideOutline',
              title: app.i10n('imagehide'),
            },
          ],
        },
      },
      data: {
        keys: {
          exit: {
            value: 'esc',
            checked: true,
            priority: 10,
          },
          exitclose: {
            value: 'x x',
            priority: 20,
          },
          imagehide: {
            value: 'h p',
            priority: 30,
          },
        },
        menu: {
          exit: {
            title: app.i10n('exit'),
            priority: 10,
          },
          exitclose: {
            title: app.i10n('exitclose'),
            priority: 20,
          },
          imagehide: {
            title: app.i10n('imagehide'),
            priority: 30,
          },
        },
        toolbar: {
          exit: {
            group: 0,
            priority: 10,
            checked: true,
            icon: 'CloseOutlined',
            title: app.i10n('exit'),
          },
          exitclose: {
            group: 0,
            priority: 20,
            icon: 'PoweroffOutlined',
            title: app.i10n('exitclose'),
          },
          imagehide: {
            group: 0,
            priority: 30,
            icon: 'ImageHideOutline',
            title: app.i10n('imagehide'),
          },
        },
        setting: {
          style_night: {
            value: true,
          },
          style_light: {
            align: 'reset',
            blockspace: '20px',
            imagealign: 'reset',
            indent: '0em',
            lineheight: 1.8,
            size: '20px',
            space: '0',
            title1: '2em',
            title1weight: 500,
            title2: '1.6em',
            title2weight: 500,
            title3: '1.2em',
            title3weight: 500,
            title4: '1em',
            title4weight: 500,
            title5: '1em',
            title5weight: 500,
            title6: '1em',
            title6weight: 500,
            titlealign: 'reset',
            weight: 400,
            width: '800px',
          },
          style_dark: {
            align: 'reset',
            blockspace: '24px',
            imagealign: 'reset',
            indent: '0em',
            lineheight: '2',
            size: '22px',
            space: 'px',
            title1: '2em',
            title1weight: 500,
            title2: '1.6em',
            title2weight: 500,
            title3: '1.2em',
            title3weight: 500,
            title4: '1em',
            title4weight: 500,
            title5: '1em',
            title5weight: 500,
            title6: '1em',
            title6weight: 500,
            titlealign: 'reset',
            weight: 400,
            width: '860px',
          },
          skin_night: {
            value: true,
          },
          skin_light: {
            color: '#1b1b1b',
            link: '#416ed2',
            hover: '#305ab7',
            visited: '#305ab7',
            select: '#1b1b1b',
            selectbg: '#bbd6fc',
            bg: '#ffffff',
            track: '#e2e2e2',
            thumb: '#9e9e9e',
            radius: '4px',
          },
          skin_dark: {
            color: '#b0b0b0',
            link: '#5ac8fa',
            hover: '#3ea4d2',
            visited: '#3ea4d2',
            select: '#fffefe',
            selectbg: '#43b0e2',
            bg: '#4a4a4d',
            track: '#4e4e50',
            thumb: '#83838c',
            radius: '4px',
          },
          theme_light: {
            value: 'light',
          },
          theme_dark: {
            value: 'gray',
          },
        },
      },
    },
    {
      id: 'react',
      title: 'react',
      core: true,
      enabled: true,
    },
    {
      id: 'plain',
      title: app.i10n('plain'),
      desc: app.i10n('plain_desc'),
      link: 'plain',
      priority: 420,
      run_at: 'load_plain',
    },
    {
      id: 'parser',
      title: app.i10n('parser'),
      core: true,
      enabled: true,
      run_at: 'load_parser',
      option: {
        apps: {
          data: [
            {
              type: 'switch',
              id: 'hide_title',
              title: app.i10n('hide_title'),
            },
            {
              type: 'switch',
              id: 'hide_date',
              title: app.i10n('hide_date'),
            },
            {
              type: 'switch',
              id: 'hide_author',
              title: app.i10n('hide_author'),
            },
            {
              type: 'switch',
              id: 'hide_excerpt',
              title: app.i10n('hide_excerpt'),
            },
            {
              type: 'switch',
              id: 'hide_read_time',
              title: app.i10n('hide_read_time'),
            },
            {
              type: 'switch',
              id: 'hide_word_count',
              title: app.i10n('hide_word_count'),
            },
            {
              type: 'switch',
              id: 'hide_cover',
              title: app.i10n('hide_cover'),
            },
            {
              type: 'switch',
              id: 'hide_tags',
              title: app.i10n('hide_tags'),
            },
          ],
        },
        keys: {
          data: {
            enter_or_exit: {
              title: app.i10n('enter_or_exit'),
            },
          },
        },
        menu: {
          data: {
            enter_or_exit: {
              title: app.i10n('enter_or_exit'),
            },
          },
        },
      },
      data: {
        keys: {
          enter_or_exit: {
            value: 'a a',
            checked: true,
          },
        },
        menu: {
          enter_or_exit: {
            title: app.i10n('enter_or_exit'),
            checked: true,
          },
        },
      },
    },
    {
      id: 'notice',
      title: app.i10n('notice'),
      core: true,
      enabled: true,
      deps: ['react', 'antd'],
      priority: 3,
      option: {
        apps: {
          data: [
            {
              type: 'select',
              defaultValue: 'top',
              id: 'notice_placement',
              title: app.i10n('notice_placement'),
              data: [
                {
                  title: app.i10n('placement_top'),
                  value: 'top',
                },
                {
                  title: app.i10n('placement_bottom'),
                  value: 'bottom',
                },
                {
                  title: app.i10n('placement_top_left'),
                  value: 'topLeft',
                },
                {
                  title: app.i10n('placement_top_right'),
                  value: 'topRight',
                },
                {
                  title: app.i10n('placement_bottom_left'),
                  value: 'bottomLeft',
                },
                {
                  title: app.i10n('placement_bottom_right'),
                  value: 'bottomRight',
                },
              ],
            },
          ],
        },
      },
    },
    {
      id: 'guide',
      title: app.i10n('guide'),
      core: true,
      enabled: true,
      deps: ['react', 'antd'],
    },
    {
      id: 'codemirror',
      title: 'codemirror',
      core: true,
      enabled: true,
    },
    {
      id: 'antd',
      title: 'antd',
      core: true,
      enabled: true,
    },
  ];
}
